=== lightofTC/CSharpHomework/XML and Its Applications/Summary/QQ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="QQ" type="QQType"/>
	<xs:complexType name="QQType">
		<xs:sequence>
			<xs:element name="category" type="typeType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="typeType">
		<xs:choice>
			<xs:element name="person" type="memberType" maxOccurs="unbounded"/>
		</xs:choice>
		<xs:attribute name="cname"/>
	</xs:complexType>
	<xs:complexType name="memberType">
		<xs:all>
			<xs:element name="number" type="numberType"/>
			<xs:element name="dname" type="stringType" minOccurs="0"/>
			<xs:element name="name" type="stringType"/>
			<xs:element name="gender" type="genderType"/>
			<xs:element name="info" type="stringType"/>
			<xs:element name="age" type="ageType"/>
			<xs:element name="zodiac" type="zodiacType"/>
			<xs:element name="level" type="ageType"/>
		</xs:all>
	</xs:complexType>
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="genderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male"/>
			<xs:enumeration value="female"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ageType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="150"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zodiacType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Capricorn"/>
			<xs:enumeration value="Aquarius"/>
			<xs:enumeration value="Pisces"/>
			<xs:enumeration value="Aries"/>
			<xs:enumeration value="Taurus"/>
			<xs:enumeration value="Gemini"/>
			<xs:enumeration value="Cancer"/>
			<xs:enumeration value="Leo"/>
			<xs:enumeration value="Virgo"/>
			<xs:enumeration value="Libra"/>
			<xs:enumeration value="Scorpio"/>
			<xs:enumeration value="Sagittarius"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="numberType">
		<xs:restriction base="xs:string">
			<xs:minLength value="7"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== lightofTC/CSharpHomework/XML and Its Applications/Summary/XQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<QQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QQ.xsd">
	<category>
		<person>
			<number>11111111</number>
			<name>ZhangSan</name>
			<gender>male</gender>
			<info>A secretary of a foreign company.</info>
			<age>45</age>
			<zodiac>Gemini</zodiac>
			<level>3</level>
		</person>
		<person>
			<number>22222222</number>
			<dname>bestFriend</dname>
			<name>LiSi</name>
			<gender>male</gender>
			<info>I like swimming.</info>
			<age>19</age>
			<zodiac>Capricorn</zodiac>
			<level>65</level>
		</person>
	</category>
	<category cname="family">
		<person>
			<number>33333333</number>
			<dname>brother</dname>
			<name>Wangwu</name>
			<gender>female</gender>
			<info>Study in PUK.</info>
			<age>23</age>
			<zodiac>Pisces</zodiac>
			<level>42</level>
		</person>
		<person>
			<number>44444444</number>
			<dname>brother</dname>
			<name>ZhaoLiu</name>
			<gender>male</gender>
			<info>A pupil</info>
			<age>10</age>
			<zodiac>Sagittarius</zodiac>
			<level>10</level>
		</person>
	</category>
	<category cname="schoolmate">
		<person>
			<number>55555555</number>
			<dname>classmate</dname>
			<name>Tianqi</name>
			<gender>male</gender>
			<info>Study harder.</info>
			<age>23</age>
			<zodiac>Aries</zodiac>
			<level>4</level>
		</person>
		<person>
			<number>66666666</number>
			<name>Cuihua</name>
			<gender>female</gender>
			<info>?????</info>
			<age>21</age>
			<zodiac>Leo</zodiac>
			<level>35</level>
		</person>
	</category>
</QQ>
