=== lightofTC/CSharpHomework/XML and Its Applications/Homework5/Lesson04_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ageType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="200"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="genderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male"/>
			<xs:enumeration value="female"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="phoneType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(\d{3}-\d{8})|(\d{4}-\d{7,8})|(1[3456789]\d{9})"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="cellphoneType">
		<xs:restriction base="phoneType">
			<xs:pattern value="1[3456789]\d{9}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="personnameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="companynameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="address_info" type="xs:string" minOccurs="1"/>
			<xs:element name="post_code" type="xs:string" minOccurs="1"/>
			<xs:element name="tips" type="xs:anySimpleType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="employeeType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="person_id" type="xs:IDREF" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:group name="baseInfo">
		<xs:sequence>
			<xs:element name="address" type="addressType"/>
			<xs:element ref="phone"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="phone" type="phoneType" block="extension"/>
	<xs:element name="cellphone" type="cellphoneType" substitutionGroup="phone"/>
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="persons"/>
				<xs:element ref="companies"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="persons">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="person_name" type="personnameType"/>
				<xs:element name="gender" type="genderType"/>
				<xs:element name="age" type="ageType"/>
				<xs:group ref="baseInfo"/>
				<xs:element name="company_affiliated">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="company_id" type="xs:IDREF" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="person_id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="companies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="company" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="company">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="company_name">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="companynameType">
								<xs:attribute name="company_type" type="xs:string" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="code" type="xs:string"/>
				<xs:group ref="baseInfo"/>
				<xs:element name="employees">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="employee" type="employeeType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="company_id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lightofTC/CSharpHomework/XML and Its Applications/Homework5/Lesson04_Schema.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Lesson04_Schema.xsd">
	<persons>
		<person person_id="f1">
			<person_name>张三</person_name>
			<gender>male</gender>
			<age>48</age>
			<address>
				<address_info>武昌区珞珈山</address_info>
				<post_code>430072</post_code>
			</address>
			<cellphone>13800000001</cellphone>
			<company_affiliated company_id="c1">武汉大学</company_affiliated>
		</person>
		<person person_id="f2">
			<person_name>李四</person_name>
			<gender>female</gender>
			<age>20</age>
			<address>
				<address_info>武昌区珞珈山</address_info>
				<post_code>430072</post_code>
			</address>
			<cellphone>13800000002</cellphone>
			<company_affiliated company_id="c1">武汉大学</company_affiliated>
		</person>
		<person person_id="f3">
			<person_name>王五</person_name>
			<gender>male</gender>
			<age>28</age>
			<address>
				<address_info>武昌区街道口</address_info>
				<post_code>430079</post_code>
			</address>
			<cellphone>13800000003</cellphone>
			<company_affiliated company_id="c2">小米武汉</company_affiliated>
		</person>
	</persons>
	<companies>
		<company company_id="c1">
			<company_name company_type="大学">武汉大学</company_name>
			<code/>
			<address>
				<address_info>武昌区珞珈山</address_info>
				<post_code>430072</post_code>
			</address>
			<phone>027-68750001</phone>
			<employees>
				<employee person_id="f1">张三</employee>
				<employee person_id="f2">李四</employee>
			</employees>
		</company>
		<company company_id="c2">
			<company_name company_type="IT企业">小米武汉</company_name>
			<code/>
			<address>
				<address_info>武昌区街道口</address_info>
				<post_code>430079</post_code>
			</address>
			<phone>027-68750001</phone>
			<employees>
				<employee person_id="f3">王五</employee>
			</employees>
		</company>
	</companies>
</root>
