=== lightofTC/CSharpHomework/XML and Its Applications/Homework3/Homework3_3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contacts (contact*)>
<!ATTLIST contacts version CDATA #FIXED "1.0">
<!ATTLIST contacts souce CDATA #IMPLIED>

<!ELEMENT contact (name, location, phone, knows, description)>
<!ATTLIST contact person ID #REQUIRED>
<!ATTLIST contact tags NMTOKENS #IMPLIED>

<!ELEMENT name (first+, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>

<!ELEMENT location (address | (latitude, longtitude))*>
<!ELEMENT address (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longtitude (#PCDATA)>

<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone kind (Home | Work | Cell | Fax) "Home">

<!ELEMENT knows EMPTY>
<!ATTLIST knows contacts IDREFS #IMPLIED>

<!ELEMENT description (#PCDATA | em | strong | br)*>
<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>
<!ELEMENT br EMPTY>

=== lightofTC/CSharpHomework/XML and Its Applications/Homework3/Homework3_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "E:\课件\大三下\XML及其应用\课堂练习\Homework3_3.dtd">
<contacts version="1.0" souce="fff">
	<contact person="c1111" tags="dd">
		<name>
			<first/>
			<middle/>
			<last/>
		</name>
		<location>
			<address>
	</address>
			<latitude>
	</latitude>
			<longtitude>
	</longtitude>
		</location>
		<phone kind="Cell"/>
		<knows contacts="c1111"/>
		<description>strong<strong/>
			<em/>
		</description>
	</contact>
</contacts>
