=== lightofTC/CSharpHomework/XML and Its Applications/Homework3/root.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT root (root1, root2?)*>
<!ELEMENT root1 (root2*)>
<!ELEMENT root2 (root3+)>
<!ELEMENT root3 (root1?)>

=== lightofTC/CSharpHomework/XML and Its Applications/Homework3/Homework3_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "D:\dtds\root.dtd">
<root>
	<root1>
    </root1>
	<root2>
		<root3>
			<root1>
		</root1>
		</root3>
	</root2>
	<root1>
		<root2>
			<root3/>
		</root2>
		<root2>
			<root3>
				<root1>
					<root2>
						<root3/>
					</root2>
				</root1>
			</root3>
		</root2>
	</root1>
</root>
